#
# Copyright 2008 Merlyn Albery-Speyer 
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
 
VERSION_NUMBER = "1.1.0"
NEXT_VERSION = "1.1.1"
GROUP = "TimeLord"
COPYRIGHT = "Merlyn Albery-Speyer 2008"
JAVASSIT = "jboss:javassist:jar:3.6.ga"
JUNIT = "junit:junit:jar:4.3.1"
JBEHAVE = "org.jbehave:jbehave:jar:1.0.1"

repositories.remote << "http://www.ibiblio.org/maven2/"

desc "The Timelord project"
define "TimeLord" do
  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT
  compile.with JAVASSIT, JUNIT, JBEHAVE
  test.compile.with JAVASSIT, JUNIT
  test.using :java_args=> [ "-Djava.system.class.loader=org.timelord.TimeLordClassLoader" ]
  
  package(:jar)
end