VERSION_NUMBER = "1.0.0"
NEXT_VERSION = "1.0.1"
GROUP = "TimeLord"
COPYRIGHT = "Merlyn Albery-Speyer"
JAVASSIT = "jboss:javassist:jar:3.6.ga"
repositories.remote << "http://www.ibiblio.org/maven2/"

desc "The Timelord project"
define "TimeLord" do
  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT
  compile.with JAVASSIT
  test.compile.with JAVASSIT
  test.using :java_args=> [ "-Djava.system.class.loader=org.timelord.TimeLordClassLoader" ]
  
  package(:jar)
end